---
- hosts: all
  tasks: 
  - name: Check motd is empty
    shell: cat /etc/motd
    register: motd_contents
  - debug: msg="stdout={{motd_contents}}"
  - debug: msg="MOTD is Empty"
    when: motd_contents.stdout == ""

