- hosts: webserver
  become: yes
  tasks:
  - name: Include vars  
    include_vars:
     file: secret.yml
  - name: Create user
    user:
     name: agent007
     comment: 'James Bond'
     password: "{{ top_secret }}"
     state: present
