---
- hosts: webserver
  vars:
   host_name: "{{ ansible_hostname }}"
  become: yes
  tasks:
  - name: Install httpd
    yum:
     name: httpd
     state: present
  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: yes
  - name: Copy the j2 template file
    template:
      src: /home/ansible/playbooks/template-examples/index.j2
      dest: /var/www/html/index.html
    notify: 
      - restart httpd
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
